# This secret is used by argocd in the argocd namespace to be able to pull services
# This is the secret to access the discovered service, it's unique for the .Values.repo
# This is accessible via https only
# It does not give access to GitHub API to create webhooks for instance
---
apiVersion: v1
kind: Secret
metadata:
  name: github-{{ .Values.repo }}-https-auth
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/{{ .Values.org }}/{{ .Values.repo }}
  password: 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
  username: not-used
